# Generated by Django 4.2.9 on 2024-02-04 02:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_searchstring'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='last_used',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
